### ISSUE TITLE
Selenium Action moveToElement doesn't work with PhantomJS 2.0.0

### ISSUE THREAD

**Issue by MelleD** [vaadin/testbench-headless-example#1]
Hi, 
I'm using this code to simulate a mouseover on a table row to have button appearing in order to click on it. This code works perfectly with firefoxDriver, but with PhantomJs, the expected button is not displayed.

``` java
Actions actions = new Actions(driver);
            actions.moveToElement(driver.findElement(tablerow));
            actions.moveToElement(driver.findElement(button));
            actions.click();
            actions.perform();
```

see https://vaadin.com/forum#!/thread/10647118

**Comment by zch** [comment]
This is not really relevant for this repository. Closing here and moving the discussion to the forum thread linked above.
